on:
  push:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: bahmutov/npm-install@v1.6.0

      - name: Install node modules
        run: |
          npm install
      - name: Run test
        run: |
          npm run test
